from pathlib import Path
import html,re,hashlib

ROOT=Path("."); AS=ROOT/"assets"/"generated-desserts"; AS.mkdir(parents=True,exist_ok=True)
recipes=[
("Tres Leches Cake","tres-leches-cake","Cake","A light sponge soaked in three milks and topped with softly whipped cream.",["5 eggs, separated","1 cup sugar","1 cup flour","1 tsp baking powder","1/3 cup whole milk","1 can evaporated milk","1 can sweetened condensed milk","1 cup heavy cream","Vanilla and cinnamon"],["Whip egg whites to soft peaks; gradually beat in sugar, then yolks.","Fold in flour and baking powder, followed by whole milk. Bake at 350°F until springy.","Pierce the cooled cake and slowly pour over evaporated milk, condensed milk, and cream.","Chill at least 4 hours. Finish with whipped cream and cinnamon."],["flan-napolitano","pastel-cajeta","carlota-limon"]),
("Churros","churros","Pastry","Crisp ridged Mexican churros rolled in cinnamon sugar, best served hot.",["1 cup water","2 tbsp sugar","1/2 tsp salt","2 tbsp butter","1 cup flour","2 eggs","Oil for frying","1/2 cup sugar + 1 tsp cinnamon"],["Bring water, sugar, salt, and butter to a boil.","Stir in flour until a smooth dough forms; cool 5 minutes, then beat in eggs.","Pipe ridged strips into 350°F oil and fry until deeply golden.","Drain and immediately toss in cinnamon sugar."],["bunuelos","gorditas-azucar","polvorones-mexicanos"]),
("Flan Napolitano","flan-napolitano","Custard","Silky Mexican caramel custard enriched with cream cheese.",["3/4 cup sugar","5 eggs","1 can evaporated milk","1 can sweetened condensed milk","4 oz cream cheese","1 tbsp vanilla"],["Caramelize sugar in a saucepan and pour into a round baking dish.","Blend eggs, both milks, cream cheese, and vanilla until smooth.","Pour over caramel and bake in a water bath at 350°F until just set, about 55 minutes.","Chill thoroughly, loosen the edge, and invert."],["chocoflan","jericalla","tres-leches-cake"]),
("Pastel de Elote","pastel-de-elote","Cake","Tender Mexican sweet-corn cake with a moist, lightly caramelized crumb.",["4 cups corn kernels","4 eggs","1 can sweetened condensed milk","1/2 cup butter, melted","1 tsp vanilla","1 cup flour","2 tsp baking powder","Pinch salt"],["Blend corn, eggs, condensed milk, butter, and vanilla until mostly smooth.","Fold in flour, baking powder, and salt.","Bake in a greased pan at 350°F until golden and a tester emerges clean.","Cool slightly and serve plain or with crema."],["tres-leches-cake","arroz-con-leche","gorditas-azucar"]),
("Arroz con Leche","arroz-con-leche","Pudding","Creamy Mexican rice pudding perfumed with cinnamon and vanilla.",["1 cup long-grain rice","2 cups water","1 cinnamon stick","4 cups whole milk","1 can sweetened condensed milk","1 tsp vanilla","Ground cinnamon"],["Simmer rice, water, and cinnamon until most water is absorbed.","Add milk and cook gently, stirring often, until the rice is tender.","Stir in condensed milk and vanilla; simmer until creamy.","Serve warm or chilled with cinnamon."],["arroz-con-leche","capirotada","jericalla"]),
("Buñuelos","bunuelos","Pastry","Thin, crisp Mexican fritters dusted generously with cinnamon sugar.",["2 cups flour","1 tsp baking powder","1 tbsp sugar","1/2 tsp salt","1 egg","3/4 cup warm water","1 tbsp butter, melted","Oil","Cinnamon sugar"],["Mix flour, baking powder, sugar, and salt; add egg, water, and butter to form a soft dough.","Rest 30 minutes, divide, and roll into very thin rounds.","Fry at 350°F until crisp and blistered on both sides.","Drain and coat with cinnamon sugar."],["churros","gorditas-azucar","orejas"]),
("Capirotada","capirotada","Bread Pudding","Traditional Mexican bread pudding layered with piloncillo syrup, fruit, nuts, and cheese.",["1 bolillo loaf, sliced and toasted","8 oz piloncillo","2 cups water","2 cinnamon sticks","3 cloves","1/2 cup raisins","1/2 cup peanuts or pecans","1 cup queso fresco or Monterey Jack"],["Simmer piloncillo, water, cinnamon, and cloves into a fragrant syrup; strain.","Layer toasted bread with raisins, nuts, and cheese.","Pour syrup evenly over the layers and let soak 10 minutes.","Bake at 350°F until bubbling and lightly browned."],["arroz-con-leche","conchas","pan-de-muerto"]),
("Conchas","conchas","Sweet Bread","Classic Mexican pan dulce with a tender enriched bun and crisp shell-pattern topping.",["4 cups bread flour","2 1/4 tsp yeast","3/4 cup warm milk","1/2 cup sugar","2 eggs","6 tbsp butter","1 tsp vanilla","Topping: 1/2 cup butter, 1/2 cup sugar, 1 cup flour"],["Knead flour, yeast, milk, sugar, eggs, butter, and vanilla until smooth; rise until doubled.","Divide and shape into buns.","Mix topping ingredients into a paste, flatten over buns, and score a shell pattern.","Proof until puffy; bake at 350°F until lightly golden."],["pan-de-muerto","orejas","marranitos"]),
("Pan de Muerto","pan-de-muerto","Sweet Bread","Orange-scented Day of the Dead bread with buttery bone-shaped decoration.",["4 cups flour","2 1/4 tsp yeast","3/4 cup warm milk","1/2 cup sugar","3 eggs","8 tbsp butter","Zest of 1 orange","1 tsp orange blossom water","Sugar for finishing"],["Knead all ingredients except finishing sugar into a supple dough; rise until doubled.","Shape rounds, reserving dough for crossed bone decorations.","Proof again and bake at 350°F until golden.","Brush warm loaves with melted butter and coat with sugar."],["conchas","orejas","marranitos"]),
("Carlota de Limón","carlota-limon","Chilled Dessert","No-bake Mexican lime icebox cake layered with cookies and tangy lime cream.",["1 can sweetened condensed milk","1 can evaporated milk","3/4 cup fresh lime juice","Zest of 2 limes","2 packages María cookies"],["Blend condensed milk, evaporated milk, lime juice, and zest until thickened.","Layer María cookies and lime cream in a dish.","Repeat, ending with cream.","Chill at least 6 hours before slicing."],["tres-leches-cake","gelatina-mosaico","fresas-con-crema"]),
("Jericalla","jericalla","Custard","Guadalajara-style baked custard with vanilla, cinnamon, and a deeply browned top.",["4 cups whole milk","1 cinnamon stick","3/4 cup sugar","6 eggs","1 tbsp vanilla"],["Heat milk with cinnamon and sugar; cool slightly and remove cinnamon.","Whisk eggs and vanilla, then slowly whisk in warm milk.","Pour into ramekins and bake in a water bath at 350°F until set.","Broil briefly to blister and brown the tops."],["flan-napolitano","arroz-con-leche","chocoflan"]),
("Chocoflan","chocoflan","Cake & Custard","The 'impossible cake': chocolate cake and caramel flan baked together in dramatic layers.",["Caramel sauce","1 chocolate cake batter","5 eggs","1 can evaporated milk","1 can condensed milk","4 oz cream cheese","1 tbsp vanilla"],["Coat a Bundt pan with caramel and add chocolate cake batter.","Blend eggs, milks, cream cheese, and vanilla; carefully pour over batter.","Cover and bake in a water bath at 350°F until set.","Chill completely and invert; the layers will have switched while baking."],["flan-napolitano","tres-leches-cake","pastel-cajeta"]),
("Pastel de Cajeta","pastel-cajeta","Cake","Moist vanilla cake layered and glazed with rich goat-milk cajeta.",["2 cups flour","2 tsp baking powder","1/2 tsp salt","3/4 cup butter","1 cup sugar","3 eggs","1 cup milk","1 tsp vanilla","1 cup cajeta"],["Whisk flour, baking powder, and salt.","Cream butter and sugar; beat in eggs, then alternate dry ingredients with milk and vanilla.","Bake at 350°F until done and cool completely.","Layer and glaze generously with cajeta."],["cajeta","empanadas-cajeta","chocoflan"]),
("Empanadas de Cajeta","empanadas-cajeta","Pastry","Flaky baked turnovers filled with thick, caramel-like cajeta.",["2 1/2 cups flour","1/2 tsp salt","8 tbsp cold butter","4 oz cream cheese","1 egg","3/4 cup thick cajeta","Cinnamon sugar"],["Cut butter and cream cheese into flour and salt; add egg and bring together.","Chill dough, then roll and cut rounds.","Fill each with cajeta, fold, crimp, and vent.","Bake at 375°F until golden; dust with cinnamon sugar."],["cajeta","pastel-cajeta","dulce-de-leche"]),
("Cocadas","cocadas","Candy","Chewy golden Mexican coconut sweets with crisp toasted edges.",["3 cups shredded coconut","3/4 cup sugar","3 egg whites","1 tsp vanilla","Pinch salt"],["Mix coconut, sugar, egg whites, vanilla, and salt.","Scoop compact mounds onto a lined baking sheet.","Bake at 325°F until golden at the edges.","Cool completely before removing."],["alegrias","mazapan-cacahuate","polvorones-mexicanos"]),
("Alegrías","alegrias","Candy","Traditional amaranth bars bound with piloncillo or honey and toasted seeds.",["3 cups popped amaranth","1/2 cup piloncillo or brown sugar","1/3 cup honey","1 tbsp lime juice","1/3 cup pumpkin seeds","1/3 cup peanuts"],["Toast seeds and combine with popped amaranth.","Cook piloncillo, honey, and lime juice to a thick syrup.","Quickly mix syrup into amaranth and press firmly into a lined pan.","Cool and cut into bars."],["mazapan-cacahuate","cocadas","camotes-poblanos"]),
("Mazapán de Cacahuate","mazapan-cacahuate","Candy","Crumbly Mexican peanut candy made with roasted peanuts and confectioners' sugar.",["2 cups roasted unsalted peanuts","1 1/2 cups confectioners' sugar","Pinch salt"],["Process peanuts until very finely ground but not yet peanut butter.","Pulse in sugar and salt until the mixture holds when pressed.","Pack firmly into small molds.","Unmold carefully and store airtight."],["alegrias","cocadas","cajeta"]),
("Camotes Poblanos","camotes-poblanos","Candy","Puebla-style sweet potato confections scented with citrus and shaped into soft candies.",["2 lb sweet potatoes","1 1/2 cups sugar","1/2 cup water","Zest of 1 orange","1 tsp vanilla"],["Bake or boil sweet potatoes until tender; peel and mash smooth.","Cook sugar and water to a syrup; stir in sweet potato, zest, and vanilla.","Cook, stirring, until thick enough to hold shape.","Cool, shape into small logs, and wrap."],["alegrias","gorditas-azucar","pastel-de-elote"]),
("Dulce de Leche","dulce-de-leche","Confection","Slow-cooked milk caramel with a deep dairy sweetness and silky texture.",["4 cups whole milk","1 1/4 cups sugar","1/4 tsp baking soda","1 tsp vanilla"],["Combine milk, sugar, and baking soda in a heavy pot.","Simmer very gently, stirring increasingly often as it darkens.","Cook until thick, glossy, and caramel-colored.","Remove from heat and stir in vanilla; cool."],["cajeta","empanadas-cajeta","pastel-cajeta"]),
("Cajeta","cajeta","Confection","Traditional Mexican goat-milk caramel, slowly reduced until glossy and deeply flavored.",["4 cups goat milk","1 1/4 cups sugar","1/4 tsp baking soda","1 tsp vanilla","1 small cinnamon stick"],["Combine goat milk, sugar, vanilla, and cinnamon; bring to a gentle simmer.","Dissolve baking soda in a spoonful of water and stir in carefully.","Cook low and slow, stirring often, until mahogany-colored and thick.","Remove cinnamon and cool."],["pastel-cajeta","empanadas-cajeta","dulce-de-leche"]),
("Paletas Mexicanas","paletas-mexicanas","Frozen Dessert","Fresh-fruit Mexican ice pops with bright lime and visible pieces of fruit.",["3 cups ripe fruit","1/3 cup sugar or honey","1/2 cup water or milk","2 tbsp lime juice","Pinch salt"],["Blend two-thirds of the fruit with sugar, liquid, lime, and salt.","Fold in remaining diced fruit.","Pour into paleta molds and insert sticks.","Freeze until solid, at least 6 hours."],["nieves-mexicanas","fresas-con-crema","gelatina-mosaico"]),
("Nieves Mexicanas","nieves-mexicanas","Frozen Dessert","Refreshing Mexican-style fruit ice churned until light and scoopable.",["4 cups ripe fruit puree","3/4 cup sugar","1 cup water","1/4 cup lime juice","Pinch salt"],["Dissolve sugar in water and cool.","Mix with fruit puree, lime, and salt.","Chill thoroughly, then churn in an ice-cream maker.","Freeze 2–3 hours to firm."],["paletas-mexicanas","fresas-con-crema","carlota-limon"]),
("Fresas con Crema","fresas-con-crema","Fruit Dessert","Fresh strawberries folded into sweet Mexican crema for a fast chilled dessert.",["1 lb strawberries, sliced","1 cup Mexican crema","1/3 cup sweetened condensed milk","1 tsp vanilla","Pinch cinnamon"],["Whisk crema, condensed milk, vanilla, and cinnamon.","Fold in sliced strawberries.","Chill 20 minutes.","Serve cold, with extra berries on top."],["paletas-mexicanas","carlota-limon","gelatina-mosaico"]),
("Plátanos Fritos con Crema","platanos-fritos-con-crema","Fruit Dessert","Caramelized ripe plantains served warm with cool crema and cinnamon.",["3 very ripe plantains","2 tbsp butter or neutral oil","Mexican crema","Cinnamon","Optional condensed milk"],["Peel and slice plantains on the bias.","Fry over medium heat until deeply caramelized on both sides.","Drain briefly.","Serve warm with crema, cinnamon, and optional condensed milk."],["platanos-fritos","fresas-con-crema","gorditas-azucar"]),
("Gorditas de Azúcar","gorditas-azucar","Sweet Bread","Soft griddled Mexican sweet cakes flavored with cinnamon and vanilla.",["3 cups flour","1/2 cup sugar","2 tsp baking powder","1/2 tsp cinnamon","Pinch salt","6 tbsp butter","1 egg","3/4 cup milk","1 tsp vanilla"],["Mix flour, sugar, baking powder, cinnamon, and salt.","Work in butter, then add egg, milk, and vanilla to make a soft dough.","Roll thick and cut rounds.","Cook on a lightly greased griddle over medium-low heat until browned and cooked through."],["bunuelos","churros","conchas"]),
("Polvorones Mexicanos","polvorones-mexicanos","Cookies","Tender, crumbly Mexican shortbread cookies with vanilla and a snowy sugar finish.",["2 cups flour","1/2 cup confectioners' sugar","1 cup butter","1 tsp vanilla","Pinch salt","Extra confectioners' sugar"],["Cream butter, sugar, vanilla, and salt.","Mix in flour just until a soft dough forms.","Shape into small rounds and bake at 325°F until set but pale.","Cool slightly and coat generously with confectioners' sugar."],["marranitos","orejas","conchas"]),
("Marranitos","marranitos","Sweet Bread","Pig-shaped Mexican gingerbread cookies sweetened with piloncillo and warm spices.",["3 cups flour","1 tsp baking soda","1 tsp cinnamon","1/2 tsp ginger","6 tbsp butter","3/4 cup piloncillo syrup","1 egg","2 tbsp milk"],["Whisk flour, baking soda, and spices.","Beat butter with piloncillo syrup and egg; add dry ingredients and enough milk for a soft dough.","Roll thick and cut with a pig-shaped cutter.","Bake at 350°F until puffed and lightly browned."],["conchas","pan-de-muerto","polvorones-mexicanos"]),
("Orejas","orejas","Pastry","Mexican bakery palmiers with crisp caramelized layers and a distinctive ear shape.",["1 lb puff pastry","3/4 cup sugar","1 tsp cinnamon"],["Mix sugar and cinnamon and coat the work surface generously.","Roll pastry lightly in sugar, fold both long edges toward the center twice, then fold together.","Slice into ears and place on a lined pan.","Bake at 400°F, turning once, until crisp and caramelized."],["conchas","pan-de-muerto","polvorones-mexicanos"]),
("Gelatina de Mosaico","gelatina-mosaico","Chilled Dessert","Colorful cubes of fruit gelatin suspended in a creamy vanilla milk gelatin.",["4 flavors fruit gelatin","1 can evaporated milk","1 can sweetened condensed milk","1 cup whole milk","3 tbsp unflavored gelatin","1 tsp vanilla"],["Prepare fruit gelatins separately using slightly less water than package directions; chill firm.","Cut into cubes and combine in a mold.","Bloom unflavored gelatin; dissolve and whisk into evaporated milk, condensed milk, whole milk, and vanilla.","Pour over cubes and chill until fully set."],["fresas-con-crema","paletas-mexicanas","carlota-limon"])
]
# Duplicate: "Arroz con Leche y Canela" is an alias of Arroz con Leche, not a second recipe.
aliases=[("arroz-con-leche-y-canela","arroz-con-leche","Arroz con Leche y Canela")]

def esc(x): return html.escape(x,quote=True)
def art(title,slug):
 h=int(hashlib.sha256(slug.encode()).hexdigest()[:8],16); hue=h%360; h2=(hue+42)%360
 return f'''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800"><defs><radialGradient id="b"><stop stop-color="hsl({hue} 38% 45%)"/><stop offset="1" stop-color="hsl({hue} 35% 14%)"/></radialGradient><radialGradient id="f"><stop stop-color="hsl({h2} 76% 70%)"/><stop offset="1" stop-color="hsl({h2} 60% 38%)"/></radialGradient></defs><rect width="1200" height="800" fill="url(#b)"/><ellipse cx="600" cy="420" rx="390" ry="240" fill="#f4ead8"/><ellipse cx="600" cy="415" rx="325" ry="180" fill="url(#f)"/><g fill="#fff1c8"><circle cx="500" cy="390" r="55"/><circle cx="640" cy="345" r="68"/><circle cx="710" cy="465" r="60"/><circle cx="550" cy="500" r="70"/></g><g fill="#c44d45"><circle cx="470" cy="330" r="26"/><circle cx="730" cy="370" r="30"/></g><path d="M520 205c-35-55 35-70 0-125M610 190c-35-55 35-70 0-125M700 205c-35-55 35-70 0-125" fill="none" stroke="white" stroke-opacity=".35" stroke-width="12"/><rect y="650" width="1200" height="150" fill="#12372c" fill-opacity=".96"/><text x="600" y="720" text-anchor="middle" fill="white" font-family="Georgia,serif" font-size="48">{esc(title)}</text><text x="600" y="765" text-anchor="middle" fill="#dec99b" font-family="Arial,sans-serif" font-size="21">THE KITCHEN TABLE · GENERATED LOCALLY</text></svg>'''

for title,slug,kind,desc,ings,steps,rels in recipes:
 (AS/f"{slug}.svg").write_text(art(title,slug),encoding="utf-8")
 related=" · ".join(f'<a class="text-link" href="{r}.html">{r.replace("-"," ").title()} →</a>' for r in rels)
 page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} | The Kitchen Table</title><link rel="stylesheet" href="styles.css"></head><body><header class="site-header"><div class="container nav-wrap"><a class="brand" href="index.html">The Kitchen Table</a><nav class="nav"><a href="index.html#recipes">Recipes</a><a href="plan-a-meal.html">Plan a Meal</a></nav></div></header><main class="section recipe-detail"><div class="container"><p class="eyebrow">MEXICAN · DESSERTS &amp; DRINKS</p><h1>{esc(title)}</h1><p class="recipe-lede">{esc(desc)}</p><img class="recipe-feature-image" src="assets/generated-desserts/{slug}.svg" alt="{esc(title)}"><div class="recipe-layout"><section><h2>Ingredients</h2><ul>{''.join(f"<li>{esc(x)}</li>" for x in ings)}</ul></section><section><h2>Method</h2><ol>{''.join(f"<li>{esc(x)}</li>" for x in steps)}</ol></section></div><div class="container" style="margin-top:28px"><h2>Related Mexican Recipes</h2><p>{related}</p></div><p><a class="text-link" href="index.html#recipes">← Back to recipes</a></p></div></main><script src="script.js"></script></body></html>'''
 (ROOT/f"{slug}.html").write_text(page,encoding="utf-8")
for slug,target,title in aliases:
 (ROOT/f"{slug}.html").write_text(f'<!doctype html><html><head><meta http-equiv="refresh" content="0; url={target}.html"><link rel="canonical" href="{target}.html"><title>{esc(title)} | The Kitchen Table</title></head><body><a href="{target}.html">Open {esc(title)}</a></body></html>',encoding="utf-8")

idx=(ROOT/"index.html").read_text(encoding="utf-8")
anchor='<div class="recipe-grid" id="recipeGrid">'
if 'tres-leches-cake.html' not in idx:
 cards=[]
 for title,slug,kind,desc,ings,steps,rels in recipes:
  search=f'{title} mexican mexico dessert desserts drinks {kind}'
  cards.append(f'''<article class="recipe-card" data-category="dessert" data-search="{esc(search)}"><img class="recipe-photo" src="assets/generated-desserts/{slug}.svg" alt="{esc(title)}"><div class="recipe-card-body"><div class="recipe-meta"><span>Mexican Dessert</span></div><h3>{esc(title)}</h3><p>{esc(desc)}</p><a href="{slug}.html" class="text-link">View recipe →</a></div></article>''')
 idx=idx.replace(anchor,anchor+"\n"+"\n".join(cards))
 (ROOT/"index.html").write_text(idx,encoding="utf-8")
print(f"Added {len(recipes)} unique Mexican desserts plus {len(aliases)} duplicate alias.")
