from pathlib import Path
from PIL import Image, ImageEnhance
import html,re

ROOT=Path("."); AS=ROOT/"assets"/"generated-broths"; AS.mkdir(parents=True,exist_ok=True)
SOURCE=Path("/tmp/broth-grid.png")

items=[
("Chicken Broth","chicken-broth","Poultry","Clean everyday chicken broth for soups, sauces, rice, and braises.",["3 lb chicken wings, backs, or legs","1 onion, quartered","2 carrots","2 celery ribs","2 garlic cloves","2 bay leaves","8 peppercorns","3 qt cold water"],["Combine everything in a stockpot and slowly bring just to a simmer.","Skim foam; keep at a bare simmer 2–3 hours.","Strain without pressing the solids.","Cool rapidly and refrigerate; remove fat if desired."],["mexican-caldo-de-pollo","ramen-chicken-broth","italian-brodo"]),
("Beef Broth","beef-broth","Meat","Deep beef broth suited to soups, sauces, braises, and onion soup.",["4 lb meaty beef bones","1 onion","2 carrots","2 celery ribs","1 tbsp tomato paste","2 bay leaves","10 peppercorns","4 qt cold water"],["Roast bones and vegetables at 425°F until well browned.","Transfer to a pot; add tomato paste, aromatics, and water.","Barely simmer 4–6 hours, skimming as needed.","Strain and cool quickly."],["beef-bone-broth","french-onion-broth","mexican-caldo-de-res"]),
("Pork Broth","pork-broth","Meat","Savory pork broth for noodles, beans, braises, and Mexican or Asian soups.",["3 lb pork neck bones or ribs","1 onion","1 carrot","4 garlic cloves","2 scallions","1 tsp peppercorns","3 qt water"],["Blanch bones 5 minutes and rinse for a cleaner broth.","Combine with aromatics and fresh water.","Simmer gently 3–4 hours.","Strain, cool, and skim fat."],["tonkotsu-broth","pozole-broth","birria-consome"]),
("Turkey Broth","turkey-broth","Poultry","A rich broth that makes excellent use of a roasted turkey carcass.",["1 turkey carcass","1 onion","2 carrots","2 celery ribs","2 bay leaves","Parsley stems","12 peppercorns","4 qt water"],["Break carcass into a stockpot and add vegetables and aromatics.","Cover with cold water and bring slowly to a simmer.","Simmer 3–4 hours without hard boiling.","Strain and chill promptly."],["chicken-broth","chicken-bone-broth","consomme"]),
("Lamb Broth","lamb-broth","Meat","Fragrant lamb broth with enough body for stews, grains, and sauces.",["3 lb lamb necks or bones","1 onion","2 carrots","2 celery ribs","3 garlic cloves","1 bay leaf","1 tsp coriander seed","3 qt water"],["Brown lamb bones in a hot oven for a deeper broth.","Add to a pot with vegetables, spices, and cold water.","Simmer gently 3–4 hours, skimming occasionally.","Strain and cool."],["beef-broth","veal-broth","consomme"]),
("Veal Broth","veal-broth","Meat","Delicate gelatin-rich veal broth, especially useful for classical sauces.",["4 lb veal bones","1 onion","2 carrots","2 celery ribs","1 tbsp tomato paste, optional","1 bay leaf","Thyme","4 qt water"],["For brown broth, roast bones and vegetables; for white broth, skip roasting.","Cover with cold water and slowly bring to a simmer.","Cook 4–6 hours, skimming frequently.","Strain through a fine sieve and chill."],["consomme","beef-broth","court-bouillon"]),
("Fish Broth","fish-broth","Seafood","Fast, clean fish broth for chowders, seafood sauces, risotto, and soups.",["2 lb non-oily white-fish bones and heads, gills removed","1 leek","1 onion","1 celery rib","1/2 cup dry white wine","Parsley stems","1 bay leaf","2 qt water"],["Rinse fish bones thoroughly.","Sweat vegetables without browning; add bones and wine.","Add water and simmer only 20–30 minutes.","Strain immediately; do not overcook."],["fish-stock","shellfish-broth","court-bouillon"]),
("Shellfish Broth","shellfish-broth","Seafood","Roasted shellfish-shell broth with concentrated ocean flavor.",["2 lb mixed shrimp, crab, or lobster shells","1 onion","1 carrot","1 celery rib","2 tbsp tomato paste","1/2 cup white wine","2 qt water"],["Roast or sauté shells until aromatic and red.","Add vegetables and tomato paste; cook until lightly caramelized.","Deglaze with wine, add water, and simmer 45 minutes.","Crush shells lightly, strain, and cool."],["shrimp-broth","lobster-broth","crab-broth"]),
("Shrimp Broth","shrimp-broth","Seafood","Quick shrimp-shell broth for gumbo, bisque, rice, sauces, and seafood soups.",["Shells from 2 lb shrimp","1 onion","1 celery rib","1 carrot","2 garlic cloves","1 tbsp tomato paste","2 qt water"],["Sauté shells until pink and fragrant.","Add vegetables and tomato paste; cook 5 minutes.","Add water and simmer 30–40 minutes.","Strain through a fine sieve."],["shellfish-broth","tom-yum-broth","spaghetti-shrimp-lemon-mint-pecorino"]),
("Lobster Broth","lobster-broth","Seafood","Luxurious roasted lobster-shell broth for bisques, sauces, and risotto.",["Shells from 2 lobsters","1 onion","1 carrot","1 celery rib","2 tbsp tomato paste","1/2 cup brandy or white wine","2 qt water"],["Crack and roast shells until deeply aromatic.","Sauté vegetables and tomato paste; add shells.","Deglaze, add water, and simmer 45–60 minutes.","Strain very well and chill."],["shellfish-broth","shrimp-broth","crab-broth"]),
("Crab Broth","crab-broth","Seafood","Sweet crab-shell broth ideal for crab soups, sauces, and seafood rice.",["2 lb crab shells and bodies","1 onion","1 carrot","1 celery rib","2 garlic cloves","1 tbsp tomato paste","2 qt water"],["Break shells into manageable pieces and roast or sauté.","Add vegetables and tomato paste; cook until fragrant.","Add water and simmer 45 minutes.","Strain carefully through a fine sieve."],["shellfish-broth","lobster-broth","shrimp-broth"]),
("Clam Broth","clam-broth","Seafood","Briny clam broth for chowders, pasta, sauces, and seafood soups.",["4 lb littleneck or cherrystone clams","2 cups water","1 cup dry white wine","2 garlic cloves","Parsley stems"],["Scrub clams thoroughly.","Steam with water, wine, garlic, and parsley until shells open.","Remove clams and strain liquid through a fine cloth to remove grit.","Use immediately or chill rapidly."],["spaghetti-with-mussels","fish-broth","shellfish-broth"]),
("Vegetable Broth","vegetable-broth","Vegetable","Versatile vegetable broth with clean sweetness and no meat.",["2 onions","3 carrots","3 celery ribs","1 leek","4 garlic cloves","1 tomato","Parsley stems","2 bay leaves","3 qt water"],["Roughly chop vegetables.","Sweat in a little oil for 10 minutes without browning.","Add herbs and water; simmer 45–60 minutes.","Strain and cool."],["mushroom-broth","parmesan-broth","seaweed-broth"]),
("Mushroom Broth","mushroom-broth","Vegetable","Earthy mushroom broth with dried shiitake for extra umami.",["1 lb fresh mushrooms","1 oz dried shiitake","1 onion","2 garlic cloves","1 tbsp soy sauce, optional","2 qt water"],["Brown fresh mushrooms deeply.","Add onion and garlic; cook until softened.","Add shiitake and water; simmer 45 minutes.","Strain, season, and cool."],["shiitake-dashi","vegetable-broth","miso-broth"]),
("Bone Broth","bone-broth","Technique","Long-simmered mixed bone broth with pronounced gelatin and body.",["4 lb mixed meaty bones","2 tbsp cider vinegar","1 onion","2 carrots","2 celery ribs","4 qt water"],["Roast bones at 425°F until browned.","Transfer to a pot with vinegar, vegetables, and cold water.","Simmer very gently 8–12 hours, adding water if necessary.","Strain and chill quickly."],["chicken-bone-broth","beef-bone-broth","beef-broth"]),
("Chicken Bone Broth","chicken-bone-broth","Poultry","Gelatin-rich chicken bone broth from carcasses, feet, wings, and aromatics.",["4 lb chicken carcasses, wings, and/or feet","1 onion","2 carrots","2 celery ribs","1 tbsp cider vinegar","4 qt water"],["Roast bones for deeper flavor, if desired.","Combine with vegetables, vinegar, and water.","Barely simmer 6–8 hours.","Strain and chill rapidly."],["chicken-broth","bone-broth","ramen-chicken-broth"]),
("Beef Bone Broth","beef-bone-broth","Meat","Long-cooked beef bone broth with roasted marrow and joint bones.",["5 lb beef marrow and joint bones","2 tbsp cider vinegar","1 onion","2 carrots","2 celery ribs","5 qt water"],["Roast bones at 425°F until deeply browned.","Place in a stockpot with vinegar, vegetables, and water.","Simmer 10–12 hours, skimming and topping up water as needed.","Strain and chill."],["beef-broth","bone-broth","pho-broth"]),
("Dashi","dashi","Japanese","Classic Japanese kombu-and-katsuobushi dashi: light, smoky, and deeply savory.",["4 cups water","1 piece kombu, about 4 inches","1 cup loosely packed katsuobushi"],["Soak kombu in water 30 minutes.","Heat slowly and remove kombu just before simmering.","Bring liquid briefly to a boil, turn off heat, and add katsuobushi.","Steep 5 minutes and strain without pressing."],["kombu-dashi","shiitake-dashi","miso-broth"]),
("Kombu Dashi","kombu-dashi","Japanese","Minimal vegan dashi extracting clean glutamate-rich flavor from kombu.",["4 cups water","1 piece kombu, about 4 inches"],["Wipe kombu gently; do not scrub away its white surface bloom.","Soak in cold water 30 minutes to overnight.","Heat slowly and remove kombu just before the water boils.","Use immediately as a soup and sauce base."],["dashi","shiitake-dashi","seaweed-broth"]),
("Shiitake Dashi","shiitake-dashi","Japanese","Vegan Japanese stock built from dried shiitake, optionally combined with kombu.",["4 cups water","6 dried shiitake mushrooms","1 piece kombu, optional"],["Rinse mushrooms quickly.","Soak mushrooms and optional kombu in cold water 4 hours or overnight.","Remove kombu before boiling; gently warm the mushroom infusion.","Strain; reserve rehydrated mushrooms for another dish."],["kombu-dashi","dashi","mushroom-broth"]),
("Tonkotsu Broth","tonkotsu-broth","Japanese","Opaque, emulsified pork-bone ramen broth produced by a vigorous long boil.",["5 lb pork neck and femur bones","1 lb pork feet","1 onion","1 head garlic","2 inches ginger","Water as needed"],["Blanch bones 10 minutes; drain and scrub thoroughly.","Cover with fresh water and boil vigorously, not gently.","Boil 10–12 hours, topping up water and stirring periodically.","Add aromatics for the final 1–2 hours; strain."],["ramen-chicken-broth","miso-broth","pork-broth"]),
("Ramen Chicken Broth","ramen-chicken-broth","Japanese","Clear but rich chicken ramen broth designed to be seasoned with a separate tare.",["4 lb chicken backs and wings","1 onion","1 leek","2 inches ginger","6 garlic cloves","1 piece kombu, optional","4 qt water"],["Blanch chicken briefly and rinse.","Cover with fresh water and maintain a gentle simmer 4 hours.","Add aromatics for the final hour.","Strain; season each bowl with tare rather than heavily salting the stock."],["tonkotsu-broth","dashi","miso-broth"]),
("Miso Broth","miso-broth","Japanese","Quick dashi-based miso broth for soup, noodles, tofu, and vegetables.",["4 cups dashi","3–4 tbsp miso paste","Tofu, wakame, and scallion, optional"],["Warm dashi to just below a simmer.","Place miso in a small bowl and whisk with a ladleful of hot dashi.","Return mixture to pot.","Do not boil after adding miso; add garnishes and serve."],["dashi","kombu-dashi","ramen-chicken-broth"]),
("Pho Broth","pho-broth","Vietnamese","Clear aromatic Vietnamese beef broth with charred onion, ginger, and warm spices.",["5 lb beef bones","1 onion, halved","4 inches ginger","3 star anise","1 cinnamon stick","4 cloves","1 tbsp coriander seed","1 tbsp fish sauce","5 qt water"],["Blanch bones, drain, and rinse thoroughly.","Char onion and ginger; toast spices.","Combine with fresh water and simmer very gently 5–6 hours.","Strain; season with fish sauce and salt."],["beef-broth","beef-bone-broth","chinese-superior-stock"]),
("Tom Yum Broth","tom-yum-broth","Thai","Hot-sour Thai broth fragrant with lemongrass, galangal, makrut lime, and chile.",["6 cups chicken or shrimp broth","2 lemongrass stalks","6 slices galangal","6 makrut lime leaves","4 Thai chiles","3 tbsp fish sauce","3 tbsp lime juice"],["Bruise lemongrass and tear lime leaves.","Simmer broth with lemongrass, galangal, leaves, and chiles 10 minutes.","Add fish sauce.","Remove from heat before adding lime juice; strain or serve rustic."],["shrimp-broth","tom-kha-broth","chicken-broth"]),
("Tom Kha Broth","tom-kha-broth","Thai","Coconut-enriched Thai broth balancing galangal, lemongrass, lime, chile, and fish sauce.",["4 cups chicken broth","2 cups coconut milk","2 lemongrass stalks","8 slices galangal","6 makrut lime leaves","3 Thai chiles","3 tbsp fish sauce","3 tbsp lime juice"],["Simmer chicken broth with aromatics 10 minutes.","Add coconut milk and return to a gentle simmer.","Season with fish sauce.","Remove from heat and add lime juice; avoid hard boiling."],["tom-yum-broth","chicken-broth","shrimp-broth"]),
("Mexican Caldo de Pollo","mexican-caldo-de-pollo","Mexican","Mexican chicken broth with vegetables, cilantro, lime, and tender bone-in chicken.",["3 lb bone-in chicken","1 onion","4 garlic cloves","2 carrots","2 zucchini","2 potatoes","2 ears corn","Cilantro","3 qt water"],["Simmer chicken, onion, garlic, and salt until chicken is tender.","Skim as needed.","Add firm vegetables first, then zucchini and corn; cook until tender.","Finish with cilantro and serve with lime."],["chicken-broth","mexican-caldo-de-res","tortillas-maiz-hechas-mano"]),
("Mexican Caldo de Res","mexican-caldo-de-res","Mexican","Hearty Mexican beef broth with shank, corn, cabbage, and root vegetables.",["3 lb beef shank or short ribs","1 onion","4 garlic cloves","2 carrots","2 potatoes","2 ears corn","1/2 cabbage","Cilantro","4 qt water"],["Simmer beef, onion, garlic, and salt until beef is nearly tender, 2–3 hours.","Skim fat and foam.","Add potatoes, carrots, and corn; add cabbage near the end.","Serve with cilantro, lime, and warm tortillas."],["beef-broth","mexican-caldo-de-pollo","tortillas-maiz-hechas-mano"]),
("Birria Consomé","birria-consome","Mexican","Chile-rich broth served alongside birria, with meat juices, spices, onion, cilantro, and lime.",["4 cups strained birria cooking liquid","1–2 cups beef broth as needed","1 tsp Mexican oregano","Salt","Chopped onion","Cilantro","Lime"],["Defat birria cooking liquid to taste, reserving some red fat if desired.","Simmer with enough beef broth to reach the preferred strength.","Season with oregano and salt.","Serve piping hot with onion, cilantro, and lime."],["birria","beef-broth","tacos-barbacoa"]),
("Pozole Broth","pozole-broth","Mexican","Red-chile pork broth base for pozole, built to carry hominy and garnishes.",["3 lb pork shoulder and neck bones","3 qt water","1 onion","4 garlic cloves","4 guajillo chiles","2 ancho chiles","1 tsp Mexican oregano"],["Simmer pork, onion, and garlic until tender.","Toast, soak, and blend chiles with some broth; strain.","Stir chile puree into broth and simmer 30 minutes.","Season with salt; add hominy when making finished pozole."],["pozole-rojo","pork-broth","mexican-caldo-de-res"]),
("Consommé","consomme","French","Crystal-clear clarified meat broth made with a traditional egg-white raft.",["2 qt well-flavored cold beef or chicken broth","1 lb lean ground meat matching broth","4 egg whites","1 onion, minced","1 carrot, minced","1 celery rib, minced","1 tomato, chopped"],["Mix cold broth with meat, egg whites, and vegetables.","Heat slowly while stirring until the raft begins to form.","Stop stirring; barely simmer 45–60 minutes, making a small opening in the raft.","Ladle clear liquid through the opening and strain through damp cheesecloth."],["beef-broth","chicken-broth","veal-broth"]),
("Court-Bouillon","court-bouillon","French","Acidulated aromatic poaching broth for fish and shellfish.",["2 qt water","1 cup dry white wine","1 onion, sliced","1 carrot, sliced","1 celery rib","1 lemon, sliced","1 bay leaf","Parsley stems","Peppercorns"],["Combine all ingredients.","Simmer 20–30 minutes to extract aromatics.","Strain if a clean poaching liquid is desired.","Use for gently poaching fish or shellfish."],["fish-broth","fish-stock","shellfish-broth"]),
("French Onion Broth","french-onion-broth","French","Deep onion-forward beef broth base for French onion soup.",["4 large onions, thinly sliced","3 tbsp butter","1 tbsp flour, optional","1/2 cup dry wine","6 cups beef broth","2 thyme sprigs","1 bay leaf"],["Caramelize onions slowly in butter until deep brown, 45–60 minutes.","Deglaze with wine and reduce.","Add beef broth, thyme, and bay.","Simmer 30 minutes and adjust seasoning."],["beef-broth","consomme","veal-broth"]),
("Italian Brodo","italian-brodo","Italian","Gentle Italian meat broth traditionally served with filled pasta or used in risotto and soups.",["2 lb beef shank","1 small chicken","1 onion","2 carrots","2 celery ribs","1 tomato","Parsley stems","4 qt water"],["Cover meats with cold water and slowly bring to a simmer.","Skim carefully.","Add vegetables and simmer very gently 3 hours.","Strain; season only after reducing or serving."],["tortellini-broth","parmesan-broth","chicken-broth"]),
("Parmesan Broth","parmesan-broth","Italian","A savory broth made from Parmesan rinds, ideal for beans, risotto, pasta, and vegetables.",["6–8 oz Parmesan rinds","1 onion","2 garlic cloves","1 bay leaf","8 cups water"],["Scrub rinds and cut into manageable pieces.","Combine with onion, garlic, bay, and water.","Barely simmer 1 1/2–2 hours, stirring occasionally to prevent sticking.","Strain while hot."],["italian-brodo","vegetable-broth","pasta-e-ceci"]),
("Tortellini Broth","tortellini-broth","Italian","Traditional brodo-style broth intended for serving tortellini in brodo.",["8 cups Italian brodo","Parmigiano rind, optional","Salt to taste","Fresh tortellini for serving"],["Bring brodo to a gentle simmer with optional Parmesan rind.","Simmer 20 minutes and remove rind.","Cook tortellini directly in the broth until tender.","Serve immediately with Parmigiano."],["italian-brodo","parmesan-broth","pasta-guide"]),
("Chinese Superior Stock","chinese-superior-stock","Chinese","Refined Chinese master stock combining chicken and pork for clear, concentrated savoriness.",["3 lb chicken backs and wings","2 lb pork bones","1 lb Jinhua ham or unsmoked ham, optional","2 inches ginger","4 scallions","5 qt water"],["Blanch chicken and pork bones; rinse thoroughly.","Combine with fresh water and slowly bring to a simmer.","Add ginger, scallions, and optional ham.","Simmer gently 4–5 hours and strain carefully."],["wonton-broth","chicken-broth","pork-broth"]),
("Wonton Broth","wonton-broth","Chinese","Light, savory broth seasoned for wontons with chicken stock, ginger, scallion, and white pepper.",["6 cups chicken or superior stock","4 slices ginger","3 scallions","1 tbsp light soy sauce","1 tsp sesame oil","White pepper","Salt"],["Simmer stock with ginger and scallion 10 minutes.","Remove aromatics.","Season lightly with soy, sesame oil, white pepper, and salt.","Ladle over freshly cooked wontons."],["chinese-superior-stock","chicken-broth","ramen-chicken-broth"]),
("Korean Anchovy Broth","korean-anchovy-broth","Korean","Korean myeolchi-yuksu made from dried anchovies, kelp, and radish.",["12 large dried anchovies, heads and guts removed","1 piece dried kelp","6 oz Korean radish","1/2 onion","8 cups water"],["Toast anchovies briefly in a dry pot, optional.","Add water, radish, onion, and kelp; soak 20 minutes.","Heat and remove kelp just before a full boil.","Simmer anchovies and vegetables 15 minutes; strain."],["seaweed-broth","kombu-dashi","dashi"]),
("Seaweed Broth","seaweed-broth","Vegetable","Clean mineral-rich seaweed broth suitable for soups, noodles, and vegetable dishes.",["8 cups water","1 oz mixed dried seaweed or kombu","2 dried shiitake, optional","2 scallions"],["Rinse seaweed briefly if sandy.","Soak in cold water 30 minutes.","Warm slowly; remove delicate seaweed before boiling.","Add optional mushrooms and scallions, simmer 10 minutes, and strain."],["kombu-dashi","korean-anchovy-broth","vegetable-broth"])
]

def esc(s): return html.escape(s,quote=True)
def svg(title,slug,i):
    # Local generated illustration; no external image dependencies.
    hue=(i*37+28)%360
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800"><defs><radialGradient id="bg"><stop stop-color="hsl({hue} 35% 42%)"/><stop offset="1" stop-color="hsl({hue} 38% 14%)"/></radialGradient><radialGradient id="s"><stop stop-color="#d9a548"/><stop offset="1" stop-color="#6e3518"/></radialGradient></defs><rect width="1200" height="800" fill="url(#bg)"/><ellipse cx="600" cy="420" rx="390" ry="235" fill="#e7ddd0"/><ellipse cx="600" cy="410" rx="330" ry="175" fill="url(#s)"/><g fill="#f2c66d" opacity=".7"><circle cx="470" cy="380" r="18"/><circle cx="710" cy="450" r="13"/><circle cx="630" cy="330" r="15"/></g><g fill="#5f9b54"><ellipse cx="530" cy="400" rx="18" ry="42" transform="rotate(45 530 400)"/><ellipse cx="690" cy="370" rx="15" ry="38" transform="rotate(-40 690 370)"/></g><path d="M500 210c-45-65 45-80 0-145M600 195c-45-65 45-80 0-145M700 210c-45-65 45-80 0-145" fill="none" stroke="#fff" stroke-opacity=".35" stroke-width="13" stroke-linecap="round"/><rect y="650" width="1200" height="150" fill="#12372c" fill-opacity=".96"/><text x="600" y="720" fill="white" font-family="Georgia,serif" font-size="50" text-anchor="middle">{esc(title)}</text><text x="600" y="765" fill="#dec99b" font-family="Arial,sans-serif" font-size="21" text-anchor="middle">THE KITCHEN TABLE · GENERATED LOCALLY</text></svg>'''

# Existing birria-consome is the canonical recipe. Do not create a duplicate page.
existing={"birria-consome"}
for i,(title,slug,region,desc,ings,steps,rels) in enumerate(items):
    (AS/f"{slug}.svg").write_text(svg(title,slug,i),encoding="utf-8")
    if slug in existing: continue
    related=" · ".join(f'<a class="text-link" href="{r}.html">{r.replace("-"," ").title()} →</a>' for r in rels)
    page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{esc(desc)}"><title>{esc(title)} | The Kitchen Table</title><link rel="stylesheet" href="styles.css"></head><body><header class="site-header"><div class="container nav-wrap"><a class="brand" href="index.html">The Kitchen Table</a><nav class="nav"><a href="index.html#recipes">Recipes</a><a href="plan-a-meal.html">Plan a Meal</a></nav></div></header><main class="section recipe-detail"><div class="container"><a class="text-link" href="index.html#recipes">← Back to all recipes</a><p class="eyebrow" style="margin-top:24px">BROTH &amp; STOCK · {esc(region.upper())}</p><h1>{esc(title)}</h1><p class="recipe-intro">{esc(desc)}</p><div class="stats"><span>Broth &amp; Stock</span><span>{esc(region)}</span></div><button class="button secondary print-button" onclick="window.print()">Print Recipe</button></div><div class="container" style="margin-top:28px"><img class="recipe-feature-image" src="assets/generated-broths/{slug}.svg" alt="{esc(title)}"></div><div class="container recipe-layout"><section class="ingredients-panel"><h2>Ingredients</h2><ul>{''.join(f"<li>{esc(x)}</li>" for x in ings)}</ul></section><section class="instructions-panel"><h2>Preparation</h2><ol>{''.join(f"<li>{esc(x)}</li>" for x in steps)}</ol></section></div><div class="container" style="margin-top:28px"><h2>Related Recipes</h2><p>{related}</p></div></main><footer class="footer"><div class="container footer-wrap"><p>© <span id="year"></span> The Kitchen Table</p><a href="index.html#recipes">All recipes</a></div></footer><script src="script.js"></script></body></html>'''
    (ROOT/f"{slug}.html").write_text(page,encoding="utf-8")

# Enhance existing canonical Birria Consomé with local generated art and related broth links.
bp=ROOT/"birria-consome.html"
if bp.exists():
    s=bp.read_text(encoding="utf-8")
    s=re.sub(r'src="[^"]+"(?=[^>]*alt="Birria con Consom)', 'src="assets/generated-broths/birria-consome.svg"', s, count=1)
    if 'Beef Broth →' not in s:
        s=s.replace("</main>",'<div class="container" style="margin-top:28px"><h2>Broth &amp; Stock Guide</h2><p><a class="text-link" href="beef-broth.html">Beef Broth →</a> · <a class="text-link" href="mexican-caldo-de-res.html">Caldo de Res →</a> · <a class="text-link" href="pozole-broth.html">Pozole Broth →</a></p></div></main>')
    bp.write_text(s,encoding="utf-8")

idx=(ROOT/"index.html").read_text(encoding="utf-8")
anchor='<div class="recipe-grid" id="recipeGrid">'
if 'chicken-broth.html' not in idx:
    cards=[]
    for title,slug,region,desc,ings,steps,rels in items:
        # Birria card already exists; avoid duplicate.
        if slug in existing: continue
        search=f"{title} broth stock soup {region}"
        cards.append(f'''<article class="recipe-card" data-category="soups" data-search="{esc(search)}"><img class="recipe-photo" src="assets/generated-broths/{slug}.svg" alt="{esc(title)}"><div class="recipe-card-body"><div class="recipe-meta"><span>Broth &amp; Stock</span><span>{esc(region)}</span></div><h3>{esc(title)}</h3><p>{esc(desc)}</p><a href="{slug}.html" class="text-link">View recipe →</a></div></article>''')
    idx=idx.replace(anchor,anchor+"\n"+"\n".join(cards))
    (ROOT/"index.html").write_text(idx,encoding="utf-8")
print("Built",len(items)-len(existing),"new broth pages; retained Birria Consomé as canonical duplicate.")
